---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: appropriate/curl

inputs:
  - name: demo-onlinestore-service

run:
  path: demo-onlinestore-service/ci/tasks/smoke.sh